-- begin KSENA_PASPORT_DATA
alter table KSENA_PASPORT_DATA add constraint FK_KSENA_PASPORT_DATA_ON_POINT foreign key (POINT_ID) references KSENA_COORDINATES(ID)^
create index IDX_KSENA_PASPORT_DATA_ON_POINT on KSENA_PASPORT_DATA (POINT_ID)^
-- end KSENA_PASPORT_DATA
-- begin KSENA_TASK_DOCUMENT
alter table KSENA_TASK_DOCUMENT add constraint FK_KSENA_TASK_DOCUMENT_ON_CLIENT foreign key (CLIENT_ID) references KSENA_PASPORT_DATA(ID)^
alter table KSENA_TASK_DOCUMENT add constraint FK_KSENA_TASK_DOCUMENT_ON_POINT foreign key (POINT_ID) references KSENA_COORDINATES(ID)^
create index IDX_KSENA_TASK_DOCUMENT_ON_CLIENT on KSENA_TASK_DOCUMENT (CLIENT_ID)^
create index IDX_KSENA_TASK_DOCUMENT_ON_POINT on KSENA_TASK_DOCUMENT (POINT_ID)^
-- end KSENA_TASK_DOCUMENT

-- begin KSENA_TASK_DOCUMENT_EMPLOYEE_LINK
alter table KSENA_TASK_DOCUMENT_EMPLOYEE_LINK add constraint FK_TASDOCEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references KSENA_PASPORT_DATA(ID)^
alter table KSENA_TASK_DOCUMENT_EMPLOYEE_LINK add constraint FK_TASDOCEMP_ON_TASK_DOCUMENT foreign key (TASK_DOCUMENT_ID) references KSENA_TASK_DOCUMENT(ID)^
-- end KSENA_TASK_DOCUMENT_EMPLOYEE_LINK
-- begin KSENA_TASK_DOCUMENT_INVENTORY_LINK
alter table KSENA_TASK_DOCUMENT_INVENTORY_LINK add constraint FK_TASDOCINV_ON_INVENTORY foreign key (INVENTORY_ID) references KSENA_INVENTORY(ID)^
alter table KSENA_TASK_DOCUMENT_INVENTORY_LINK add constraint FK_TASDOCINV_ON_TASK_DOCUMENT foreign key (TASK_DOCUMENT_ID) references KSENA_TASK_DOCUMENT(ID)^
-- end KSENA_TASK_DOCUMENT_INVENTORY_LINK
