alter table KSENA_TASK_DOCUMENT add constraint FK_KSENA_TASK_DOCUMENT_ON_EMPLOYEES foreign key (EMPLOYEES_ID) references KSENA_PASPORT_DATA(ID);
create index IDX_KSENA_TASK_DOCUMENT_ON_EMPLOYEES on KSENA_TASK_DOCUMENT (EMPLOYEES_ID);
