alter table KSENA_PASPORT_DATA add constraint FK_KSENA_PASPORT_DATA_ON_MOBILE_PHONE foreign key (MOBILE_PHONE_ID) references KSENA_MOBILE_PHONE(ID);
create index IDX_KSENA_PASPORT_DATA_ON_MOBILE_PHONE on KSENA_PASPORT_DATA (MOBILE_PHONE_ID);
