alter table KSENA_MOBILE_PHONE add constraint FK_KSENA_MOBILE_PHONE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references KSENA_PASPORT_DATA(ID);
create index IDX_KSENA_MOBILE_PHONE_ON_EMPLOYEE on KSENA_MOBILE_PHONE (EMPLOYEE_ID);
