alter table KSENA_PASPORT_DATA add constraint FK_KSENA_PASPORT_DATA_ON_POINT foreign key (POINT_ID) references KSENA_COORDINATES(ID);
create index IDX_KSENA_PASPORT_DATA_ON_POINT on KSENA_PASPORT_DATA (POINT_ID);
