alter table KSENA_INVENTORY add constraint FK_KSENA_INVENTORY_ON_TASK_DOCUMENT foreign key (TASK_DOCUMENT_ID) references KSENA_TASK_DOCUMENT(ID);
create index IDX_KSENA_INVENTORY_ON_TASK_DOCUMENT on KSENA_INVENTORY (TASK_DOCUMENT_ID);
