alter table KSENA_TASK_DOCUMENT add constraint FK_KSENA_TASK_DOCUMENT_ON_CLIENT foreign key (CLIENT_ID) references KSENA_CLIENT(ID);
create index IDX_KSENA_TASK_DOCUMENT_ON_CLIENT on KSENA_TASK_DOCUMENT (CLIENT_ID);
