alter table KSENA_PASPORT_DATA add constraint FK_KSENA_PASPORT_DATA_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID);
create index IDX_KSENA_PASPORT_DATA_ON_IMAGE_FILE on KSENA_PASPORT_DATA (IMAGE_FILE_ID);
