alter table KSENA_PASPORT_DATA add constraint FK_KSENA_PASPORT_DATA_ON_COMPANY foreign key (COMPANY_ID) references KSENA_COMPANY(ID);
create index IDX_KSENA_PASPORT_DATA_ON_COMPANY on KSENA_PASPORT_DATA (COMPANY_ID);
