alter table KSENA_TASK_DOCUMENT add constraint FK_KSENA_TASK_DOCUMENT_ON_COMPANY foreign key (COMPANY_ID) references KSENA_COMPANY(ID);
create index IDX_KSENA_TASK_DOCUMENT_ON_COMPANY on KSENA_TASK_DOCUMENT (COMPANY_ID);
