create table KSENA_CLEANING_POSITION_QUANTITY_POSITION_LINK (
    QUANTITY_POSITION_ID varchar(36) not null,
    CLEANING_POSITION_ID varchar(36) not null,
    primary key (QUANTITY_POSITION_ID, CLEANING_POSITION_ID)
);
