alter table KSENA_TASK add constraint FK_KSENA_TASK_ON_TASK_DOCUMENT foreign key (TASK_DOCUMENT_ID) references KSENA_TASK_DOCUMENT(ID);
create index IDX_KSENA_TASK_ON_TASK_DOCUMENT on KSENA_TASK (TASK_DOCUMENT_ID);
