alter table KSENA_CLEANING_POSITION add constraint FK_KSENA_CLEANING_POSITION_ON_ROOM foreign key (ROOM_ID) references KSENA_ROOM(ID);
create index IDX_KSENA_CLEANING_POSITION_ON_ROOM on KSENA_CLEANING_POSITION (ROOM_ID);
