alter table KSENA_BREAKAGE add constraint FK_KSENA_BREAKAGE_ON_INVENTORY foreign key (INVENTORY_ID) references KSENA_INVENTORY(ID);
create index IDX_KSENA_BREAKAGE_ON_INVENTORY on KSENA_BREAKAGE (INVENTORY_ID);
