alter table KSENA_CLEANING_POSITION alter column VISIBLE rename to VISIBLE__U50839 ^
alter table KSENA_CLEANING_POSITION alter column NOTE_CLEANING_POSITION rename to NOTE_CLEANING_POSITION__U04185 ^
alter table KSENA_CLEANING_POSITION alter column PRIORITY_CLEANING_POSITION rename to PRIORITY_CLEANING_POSITION__U06222 ^
