alter table KSENA_CLEANING_POSITION drop column PRIORITY_CLEANING_POSITION__U06222 cascade ;
alter table KSENA_CLEANING_POSITION drop column NOTE_CLEANING_POSITION__U04185 cascade ;
alter table KSENA_CLEANING_POSITION drop column VISIBLE__U50839 cascade ;
