alter table KSENA_COORDINATES add constraint FK_KSENA_COORDINATES_ON_COMPANY foreign key (COMPANY_ID) references KSENA_COMPANY(ID);
create index IDX_KSENA_COORDINATES_ON_COMPANY on KSENA_COORDINATES (COMPANY_ID);
