alter table KSENA_CLEANING_POSITION alter column ROOM_ID rename to ROOM_ID__U04694 ^
alter table KSENA_CLEANING_POSITION drop constraint FK_KSENA_CLEANING_POSITION_ON_ROOM ;
drop index IDX_KSENA_CLEANING_POSITION_ON_ROOM ;
