alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID);
create index IDX_KSENA_POSITION_WRAPPER_ON_TASK on KSENA_POSITION_WRAPPER (TASK_ID);
