alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_POSITION foreign key (POSITION_ID) references KSENA_CLEANING_POSITION(ID);
create index IDX_KSENA_POSITION_WRAPPER_ON_POSITION on KSENA_POSITION_WRAPPER (POSITION_ID);
