alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_ROOM_NAME foreign key (ROOM_NAME_ID) references KSENA_ROOM(ID);
create index IDX_KSENA_POSITION_WRAPPER_ON_ROOM_NAME on KSENA_POSITION_WRAPPER (ROOM_NAME_ID);
