alter table KSENA_INVENTORY_WRAPPER add constraint FK_KSENA_INVENTORY_WRAPPER_ON_INVENTORY foreign key (INVENTORY_ID) references KSENA_INVENTORY(ID);
create index IDX_KSENA_INVENTORY_WRAPPER_ON_INVENTORY on KSENA_INVENTORY_WRAPPER (INVENTORY_ID);
