alter table KSENA_INVENTORY_WRAPPER add constraint FK_KSENA_INVENTORY_WRAPPER_ON_INVENTORY foreign key (INVENTORY_ID) references KSENA_INVENTORY(ID);
alter table KSENA_INVENTORY_WRAPPER add constraint FK_KSENA_INVENTORY_WRAPPER_ON_TASK_DOCUMENTS foreign key (TASK_DOCUMENTS_ID) references KSENA_TASK_DOCUMENT(ID);
alter table KSENA_INVENTORY_WRAPPER add constraint FK_KSENA_INVENTORY_WRAPPER_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID);
create index IDX_KSENA_INVENTORY_WRAPPER_ON_INVENTORY on KSENA_INVENTORY_WRAPPER (INVENTORY_ID);
create index IDX_KSENA_INVENTORY_WRAPPER_ON_TASK_DOCUMENTS on KSENA_INVENTORY_WRAPPER (TASK_DOCUMENTS_ID);
create index IDX_KSENA_INVENTORY_WRAPPER_ON_TASK on KSENA_INVENTORY_WRAPPER (TASK_ID);
