alter table KSENA_INVENTORY alter column VISIBLE rename to VISIBLE__U11927 ^
alter table KSENA_INVENTORY alter column NOTE_INVENTORY rename to NOTE_INVENTORY__U98787 ^
alter table KSENA_INVENTORY alter column QUANTITY_INVENTORY rename to QUANTITY_INVENTORY__U20910 ^
