alter table KSENA_COMPANY add constraint FK_KSENA_COMPANY_ON_COMPANY_CATEGORY foreign key (COMPANY_CATEGORY_ID) references KSENA_COMPANY_CATEGORY(ID);
create index IDX_KSENA_COMPANY_ON_COMPANY_CATEGORY on KSENA_COMPANY (COMPANY_CATEGORY_ID);
