alter table KSENA_CLIENT_EMPLOYEE add constraint FK_KSENA_CLIENT_EMPLOYEE_ON_COMPANIES foreign key (COMPANIES_ID) references KSENA_COMPANY(ID);
create index IDX_KSENA_CLIENT_EMPLOYEE_ON_COMPANIES on KSENA_CLIENT_EMPLOYEE (COMPANIES_ID);
