alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_TEMPLATE foreign key (TEMPLATE_ID) references KSENA_TEMPLATE(ID);
create index IDX_KSENA_POSITION_WRAPPER_ON_TEMPLATE on KSENA_POSITION_WRAPPER (TEMPLATE_ID);
