alter table KSENA_TASK add constraint FK_KSENA_TASK_ON_KIND_OF_CLEANING foreign key (KIND_OF_CLEANING_ID) references KSENA_KIND_OF_CLEANING(ID);
create index IDX_KSENA_TASK_ON_KIND_OF_CLEANING on KSENA_TASK (KIND_OF_CLEANING_ID);
