-- begin KSENA_MOBILE_PHONE
alter table KSENA_MOBILE_PHONE add constraint FK_KSENA_MOBILE_PHONE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references KSENA_EMPLOYEE(ID)^
create index IDX_KSENA_MOBILE_PHONE_ON_EMPLOYEE on KSENA_MOBILE_PHONE (EMPLOYEE_ID)^
-- end KSENA_MOBILE_PHONE
-- begin KSENA_POSITION_WRAPPER
alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_POSITION foreign key (POSITION_ID) references KSENA_CLEANING_POSITION(ID)^
alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_TEMPLATE foreign key (TEMPLATE_ID) references KSENA_TEMPLATE(ID)^
alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_TASK_DOCUMENTS foreign key (TASK_DOCUMENTS_ID) references KSENA_TASK_DOCUMENT(ID)^
alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID)^
alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_ROOM_NAME foreign key (ROOM_NAME_ID) references KSENA_ROOM(ID)^
create index IDX_KSENA_POSITION_WRAPPER_ON_POSITION on KSENA_POSITION_WRAPPER (POSITION_ID)^
create index IDX_KSENA_POSITION_WRAPPER_ON_TEMPLATE on KSENA_POSITION_WRAPPER (TEMPLATE_ID)^
create index IDX_KSENA_POSITION_WRAPPER_ON_TASK_DOCUMENTS on KSENA_POSITION_WRAPPER (TASK_DOCUMENTS_ID)^
create index IDX_KSENA_POSITION_WRAPPER_ON_TASK on KSENA_POSITION_WRAPPER (TASK_ID)^
create index IDX_KSENA_POSITION_WRAPPER_ON_ROOM_NAME on KSENA_POSITION_WRAPPER (ROOM_NAME_ID)^
-- end KSENA_POSITION_WRAPPER
-- begin KSENA_BREAKAGE
alter table KSENA_BREAKAGE add constraint FK_KSENA_BREAKAGE_ON_INVENTORY foreign key (INVENTORY_ID) references KSENA_INVENTORY(ID)^
create index IDX_KSENA_BREAKAGE_ON_INVENTORY on KSENA_BREAKAGE (INVENTORY_ID)^
-- end KSENA_BREAKAGE
-- begin KSENA_COORDINATES
alter table KSENA_COORDINATES add constraint FK_KSENA_COORDINATES_ON_COMPANY foreign key (COMPANY_ID) references KSENA_COMPANY(ID)^
create index IDX_KSENA_COORDINATES_ON_COMPANY on KSENA_COORDINATES (COMPANY_ID)^
-- end KSENA_COORDINATES
-- begin KSENA_COMPANY
alter table KSENA_COMPANY add constraint FK_KSENA_COMPANY_ON_FIELD_OF_ACTIVITY foreign key (FIELD_OF_ACTIVITY_ID) references KSENA_FIELD_OF_ACTIVITY(ID)^
alter table KSENA_COMPANY add constraint FK_KSENA_COMPANY_ON_COMPANY_TYPE foreign key (COMPANY_TYPE_ID) references KSENA_COMPANY_TYPE(ID)^
alter table KSENA_COMPANY add constraint FK_KSENA_COMPANY_ON_COMPANY_CATEGORY foreign key (COMPANY_CATEGORY_ID) references KSENA_COMPANY_CATEGORY(ID)^
create index IDX_KSENA_COMPANY_ON_FIELD_OF_ACTIVITY on KSENA_COMPANY (FIELD_OF_ACTIVITY_ID)^
create index IDX_KSENA_COMPANY_ON_COMPANY_TYPE on KSENA_COMPANY (COMPANY_TYPE_ID)^
create index IDX_KSENA_COMPANY_ON_COMPANY_CATEGORY on KSENA_COMPANY (COMPANY_CATEGORY_ID)^
-- end KSENA_COMPANY
-- begin KSENA_TASK
alter table KSENA_TASK add constraint FK_KSENA_TASK_ON_KIND_OF_CLEANING foreign key (KIND_OF_CLEANING_ID) references KSENA_KIND_OF_CLEANING(ID)^
alter table KSENA_TASK add constraint FK_KSENA_TASK_ON_TASK_DOCUMENT foreign key (TASK_DOCUMENT_ID) references KSENA_TASK_DOCUMENT(ID)^
alter table KSENA_TASK add constraint FK_KSENA_TASK_ON_COMPANY foreign key (COMPANY_ID) references KSENA_COMPANY(ID)^
alter table KSENA_TASK add constraint FK_KSENA_TASK_ON_POINT foreign key (POINT_ID) references KSENA_COORDINATES(ID)^
create unique index IDX_KSENA_TASK_UK_TASK_NUMBER on KSENA_TASK (TASK_NUMBER) where DELETE_TS is null ^
create index IDX_KSENA_TASK_ON_KIND_OF_CLEANING on KSENA_TASK (KIND_OF_CLEANING_ID)^
create index IDX_KSENA_TASK_ON_TASK_DOCUMENT on KSENA_TASK (TASK_DOCUMENT_ID)^
create index IDX_KSENA_TASK_ON_COMPANY on KSENA_TASK (COMPANY_ID)^
create index IDX_KSENA_TASK_ON_POINT on KSENA_TASK (POINT_ID)^
-- end KSENA_TASK
-- begin KSENA_GOOGLE_CALENDAR_EVENT_ID
alter table KSENA_GOOGLE_CALENDAR_EVENT_ID add constraint FK_KSENA_GOOGLE_CALENDAR_EVENT_ID_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID)^
create index IDX_KSENA_GOOGLE_CALENDAR_EVENT_ID_ON_TASK on KSENA_GOOGLE_CALENDAR_EVENT_ID (TASK_ID)^
-- end KSENA_GOOGLE_CALENDAR_EVENT_ID
-- begin KSENA_TASK_DOCUMENT
alter table KSENA_TASK_DOCUMENT add constraint FK_KSENA_TASK_DOCUMENT_ON_POINT foreign key (POINT_ID) references KSENA_COORDINATES(ID)^
alter table KSENA_TASK_DOCUMENT add constraint FK_KSENA_TASK_DOCUMENT_ON_COMPANY foreign key (COMPANY_ID) references KSENA_COMPANY(ID)^
create index IDX_KSENA_TASK_DOCUMENT_ON_POINT on KSENA_TASK_DOCUMENT (POINT_ID)^
create index IDX_KSENA_TASK_DOCUMENT_ON_COMPANY on KSENA_TASK_DOCUMENT (COMPANY_ID)^
-- end KSENA_TASK_DOCUMENT
-- begin KSENA_INVENTORY_WRAPPER
alter table KSENA_INVENTORY_WRAPPER add constraint FK_KSENA_INVENTORY_WRAPPER_ON_INVENTORY foreign key (INVENTORY_ID) references KSENA_INVENTORY(ID)^
alter table KSENA_INVENTORY_WRAPPER add constraint FK_KSENA_INVENTORY_WRAPPER_ON_TASK_DOCUMENTS foreign key (TASK_DOCUMENTS_ID) references KSENA_TASK_DOCUMENT(ID)^
alter table KSENA_INVENTORY_WRAPPER add constraint FK_KSENA_INVENTORY_WRAPPER_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID)^
create index IDX_KSENA_INVENTORY_WRAPPER_ON_INVENTORY on KSENA_INVENTORY_WRAPPER (INVENTORY_ID)^
create index IDX_KSENA_INVENTORY_WRAPPER_ON_TASK_DOCUMENTS on KSENA_INVENTORY_WRAPPER (TASK_DOCUMENTS_ID)^
create index IDX_KSENA_INVENTORY_WRAPPER_ON_TASK on KSENA_INVENTORY_WRAPPER (TASK_ID)^
-- end KSENA_INVENTORY_WRAPPER
-- begin KSENA_EMPLOYEE
alter table KSENA_EMPLOYEE add constraint FK_KSENA_EMPLOYEE_ON_MOBILE_PHONE foreign key (MOBILE_PHONE_ID) references KSENA_MOBILE_PHONE(ID)^
alter table KSENA_EMPLOYEE add constraint FK_KSENA_EMPLOYEE_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
create index IDX_KSENA_EMPLOYEE_ON_MOBILE_PHONE on KSENA_EMPLOYEE (MOBILE_PHONE_ID)^
create index IDX_KSENA_EMPLOYEE_ON_IMAGE_FILE on KSENA_EMPLOYEE (IMAGE_FILE_ID)^
-- end KSENA_EMPLOYEE
-- begin KSENA_CLIENT_EMPLOYEE
alter table KSENA_CLIENT_EMPLOYEE add constraint FK_KSENA_CLIENT_EMPLOYEE_ON_COMPANIES foreign key (COMPANIES_ID) references KSENA_COMPANY(ID)^
create index IDX_KSENA_CLIENT_EMPLOYEE_ON_COMPANIES on KSENA_CLIENT_EMPLOYEE (COMPANIES_ID)^
-- end KSENA_CLIENT_EMPLOYEE
-- begin KSENA_TASK_DOCUMENT_DAY_INTERVAL_LINK
alter table KSENA_TASK_DOCUMENT_DAY_INTERVAL_LINK add constraint FK_TASDOCDAYINT_ON_TASK_DOCUMENT foreign key (TASK_DOCUMENT_ID) references KSENA_TASK_DOCUMENT(ID)^
alter table KSENA_TASK_DOCUMENT_DAY_INTERVAL_LINK add constraint FK_TASDOCDAYINT_ON_DAY_INTERVAL foreign key (DAY_INTERVAL_ID) references KSENA_DAY_INTERVAL(ID)^
-- end KSENA_TASK_DOCUMENT_DAY_INTERVAL_LINK
-- begin KSENA_TASK_DOCUMENT_EMPLOYEE_LINK
alter table KSENA_TASK_DOCUMENT_EMPLOYEE_LINK add constraint FK_TASDOCEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references KSENA_EMPLOYEE(ID)^
alter table KSENA_TASK_DOCUMENT_EMPLOYEE_LINK add constraint FK_TASDOCEMP_ON_TASK_DOCUMENT foreign key (TASK_DOCUMENT_ID) references KSENA_TASK_DOCUMENT(ID)^
-- end KSENA_TASK_DOCUMENT_EMPLOYEE_LINK
-- begin KSENA_TASK_INVENTORY_LINK
alter table KSENA_TASK_INVENTORY_LINK add constraint FK_TASINV_ON_INVENTORY foreign key (INVENTORY_ID) references KSENA_INVENTORY(ID)^
alter table KSENA_TASK_INVENTORY_LINK add constraint FK_TASINV_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID)^
-- end KSENA_TASK_INVENTORY_LINK
-- begin KSENA_CLIENT_EMPLOYEE_POINT_LINK
alter table KSENA_CLIENT_EMPLOYEE_POINT_LINK add constraint FK_CLIEMPPOI_ON_CLIENT_EMPLOYEE foreign key (CLIENT_EMPLOYEE_ID) references KSENA_CLIENT_EMPLOYEE(ID)^
alter table KSENA_CLIENT_EMPLOYEE_POINT_LINK add constraint FK_CLIEMPPOI_ON_POINT foreign key (POINT_ID) references KSENA_COORDINATES(ID)^
-- end KSENA_CLIENT_EMPLOYEE_POINT_LINK
-- begin KSENA_TASK_CLEANING_POSITION_LINK
alter table KSENA_TASK_CLEANING_POSITION_LINK add constraint FK_TASCLEPOS_ON_CLEANING_POSITION foreign key (CLEANING_POSITION_ID) references KSENA_CLEANING_POSITION(ID)^
alter table KSENA_TASK_CLEANING_POSITION_LINK add constraint FK_TASCLEPOS_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID)^
-- end KSENA_TASK_CLEANING_POSITION_LINK
-- begin KSENA_CLEANING_POSITION_EXPENDABLE_MATERIAL_LINK
alter table KSENA_CLEANING_POSITION_EXPENDABLE_MATERIAL_LINK add constraint FK_CLEPOSEXPMAT_ON_CLEANING_POSITION foreign key (CLEANING_POSITION_ID) references KSENA_CLEANING_POSITION(ID)^
alter table KSENA_CLEANING_POSITION_EXPENDABLE_MATERIAL_LINK add constraint FK_CLEPOSEXPMAT_ON_EXPENDABLE_MATERIAL foreign key (EXPENDABLE_MATERIAL_ID) references KSENA_EXPENDABLE_MATERIAL(ID)^
-- end KSENA_CLEANING_POSITION_EXPENDABLE_MATERIAL_LINK
-- begin KSENA_TASK_EMPLOYEE_LINK
alter table KSENA_TASK_EMPLOYEE_LINK add constraint FK_TASEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references KSENA_EMPLOYEE(ID)^
alter table KSENA_TASK_EMPLOYEE_LINK add constraint FK_TASEMP_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID)^
-- end KSENA_TASK_EMPLOYEE_LINK
