alter table KSENA_EMPLOYEE add constraint FK_KSENA_EMPLOYEE_ON_MOBILE_PHONE foreign key (MOBILE_PHONE_ID) references KSENA_MOBILE_PHONE(ID);
alter table KSENA_EMPLOYEE add constraint FK_KSENA_EMPLOYEE_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID);
create index IDX_KSENA_EMPLOYEE_ON_MOBILE_PHONE on KSENA_EMPLOYEE (MOBILE_PHONE_ID);
create index IDX_KSENA_EMPLOYEE_ON_IMAGE_FILE on KSENA_EMPLOYEE (IMAGE_FILE_ID);
