create table KSENA_EMPLOYEE (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    FULL_NAME varchar(255),
    EMAIL varchar(255),
    PHONE_NUMBER integer,
    PASPORT_NUMBER varchar(2),
    AUTHORITY varchar(255),
    DATE_OF_ISSUE date,
    INDIVIDUAL_TAXPAYER_NUMBER varchar(255),
    SEX varchar(50),
    --
    EMPLOYEE_TYPE varchar(50),
    IS_ACTIVE boolean,
    QUALIFICATION varchar(50),
    MOBILE_PHONE_ID uuid,
    DATE_OF_EMPLOYMENT date,
    DATE_OF_DISMISSAL date,
    IMAGE_FILE_ID uuid,
    RESIDENCE_NUMBER varchar(255),
    RESIDENCE_PERMANENT boolean,
    RESIDENCE_END_TIME date,
    RESIDENCE_ADDRESS varchar(255),
    RESIDENCE_PLACE varchar(255),
    --
    primary key (ID)
);