alter table KSENA_CLEANING_POSITION rename column visible to visible__u80237 ;
alter table KSENA_CLEANING_POSITION rename column priority_cleaning_position to priority_cleaning_position__u30592 ;
alter table KSENA_CLEANING_POSITION rename column note_cleaning_position to note_cleaning_position__u17211 ;
