alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_POSITION foreign key (POSITION_ID) references KSENA_CLEANING_POSITION(ID);
alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_TASK_DOCUMENTS foreign key (TASK_DOCUMENTS_ID) references KSENA_TASK_DOCUMENT(ID);
alter table KSENA_POSITION_WRAPPER add constraint FK_KSENA_POSITION_WRAPPER_ON_TASK foreign key (TASK_ID) references KSENA_TASK(ID);
create index IDX_KSENA_POSITION_WRAPPER_ON_POSITION on KSENA_POSITION_WRAPPER (POSITION_ID);
create index IDX_KSENA_POSITION_WRAPPER_ON_TASK_DOCUMENTS on KSENA_POSITION_WRAPPER (TASK_DOCUMENTS_ID);
create index IDX_KSENA_POSITION_WRAPPER_ON_TASK on KSENA_POSITION_WRAPPER (TASK_ID);
